#!/usr/bin/env python
# manage.py is the settings bootstrapper; pylint-django cannot see the runtime
# DJANGO_SETTINGS_MODULE, so its django-not-configured fires spuriously here.
# pylint: disable=django-not-configured
"""Django management entry (generated by racecar-create-server)."""
import os
import sys

if __name__ == "__main__":
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "project.settings.api")
    from django.core.management import execute_from_command_line

    execute_from_command_line(sys.argv)
