#!/usr/bin/env python3
"""scaffold_surfaces_docs.py — the generated-docs half of the surface templates.

The OpenAPI document, the human/LLM ENDPOINTS.md, and the GET-endpoint sitemap, all derived
from the one Interface Manifest. Split out of scaffold_surfaces_templates.py to keep each
module focused (and under the module-size limit); the writers there import these. Public
(no leading underscore) because they are imported across modules.
"""
import json


def openapi_doc(manifest: dict) -> str:
    """OpenAPI 3.1 document for the REST surface, built from the manifest. GET commands
    expose query parameters; non-GET commands take the input_schema as a JSON body."""
    paths: dict = {}
    tags = []
    seen = set()
    scopes: dict = {}
    for v in manifest["verticals"]:
        tag = v["app"]
        if tag not in seen:
            seen.add(tag)
            tags.append({"name": tag, "description": f"{v['vertical']} endpoints"})
        for c in v["commands"]:
            method = c["method"].lower()
            schema = c["input_schema"]
            scope = c.get("scope", "")
            if scope:
                scopes[scope] = f"Access {c['mcp_tool']}"
            op = {
                "operationId": c["mcp_tool"],
                "summary": c["description"] or c["subcommand"],
                "tags": [tag],
                "security": [{"oauth2": [scope] if scope else []}],
                "responses": {
                    "200": {"description": "Success"},
                    "401": {"description": "Missing or invalid bearer token"},
                    "403": {"description": "Insufficient scope, or writes disabled"},
                },
            }
            if method == "get":
                props = schema.get("properties", {})
                required = set(schema.get("required", []))
                op["parameters"] = [
                    {"name": k, "in": "query", "required": k in required, "schema": s}
                    for k, s in props.items()
                ]
            else:
                op["requestBody"] = {
                    "required": bool(schema.get("required")),
                    "content": {"application/json": {"schema": schema}},
                }
            paths.setdefault(c["http_path"], {})[method] = op
    doc = {
        "openapi": "3.1.0",
        "info": {
            "title": f"{manifest['package']} REST API",
            "version": "1.0.0",
            "description": (
                "Generated by racecar-create-server. All routes are under /api/v1/. Closed by "
                "default: every route needs an OAuth 2.1 bearer token carrying its scope "
                "(401 without a valid token, 403 out of scope). Write verbs (any non-GET) "
                "are additionally gated by RACECAR_ALLOW_WRITES. MCP is a separate "
                "server at /mcp."
            ),
        },
        "servers": [{"url": "/", "description": "This host"}],
        "tags": tags,
        "paths": paths,
        "components": {
            "securitySchemes": {
                "oauth2": {
                    "type": "oauth2",
                    "description": (
                        "OAuth 2.1 opaque bearer token from the Authorization Server; "
                        "validated by introspection. Closed by default (AUTH.md)."
                    ),
                    "flows": {
                        "authorizationCode": {
                            "authorizationUrl": "/o/authorize/",
                            "tokenUrl": "/o/token/",
                            "scopes": scopes,
                        }
                    },
                }
            }
        },
        "security": [{"oauth2": []}],
    }
    return json.dumps(doc, indent=2) + "\n"


def endpoints_md(manifest: dict) -> str:
    """Human + LLM endpoint list: the REST routes and the MCP tools, one table each."""
    rest, mcp = [], []
    for v in manifest["verticals"]:
        for c in v["commands"]:
            rest.append(
                f'| {c["method"].upper()} | `{c["http_path"]}` | '
                f'{"yes" if c["is_write"] else "no"} | {c["description"]} |'
            )
            mcp.append(
                f'| `{c["mcp_tool"]}` | {"no" if c["is_write"] else "yes"} | {c["description"]} |'
            )
    rest_tbl = "\n".join(rest)
    mcp_tbl = "\n".join(mcp)
    return f'''# {manifest["package"]} surface — endpoints

Generated by racecar-create-server from the Interface Manifest. Two surfaces over the same
`api`: REST on `api.*` (host-routed), MCP on `mcp.*`. Machine spec:
[`openapi.json`](openapi.json).

## REST endpoints (`/api/v1/<vertical-path>/<command>`)

| Method | Path | Write | Description |
|---|---|---|---|
{rest_tbl}

The OpenAPI document is served at `/api/v1/openapi.json`; the crawlable GET
surface is listed at `/sitemap/` and `/sitemap.xml/`.

## MCP tools (one Streamable-HTTP server at `/mcp`)

| Tool | Read-only | Description |
|---|---|---|
{mcp_tbl}

Write verbs (any non-GET / non-read-only) are refused unless
`RACECAR_ALLOW_WRITES=1`.
'''


def sitemaps_py(manifest: dict) -> str:
    """project/sitemaps.py: a sitemap of the REST GET endpoints (house pattern)."""
    get_paths = [
        c["http_path"]
        for v in manifest["verticals"]
        for c in v["commands"]
        if c["method"].upper() == "GET"
    ]
    paths_block = "\n".join(f'    "{p}",' for p in get_paths)
    return f'''"""Sitemap of the REST API's GET endpoints (house pattern, a-la eninesites). The
domain comes from the request host via get_domain, so no django.contrib.sites
dependency is needed.
"""
from django.contrib.sitemaps import Sitemap
from django.contrib.sitemaps.views import sitemap as _sitemap_view

# Generated: the GET endpoints of the REST surface (the crawlable surface).
GET_ENDPOINTS = [
{paths_block}
]


def custom_sitemap(request, sitemaps):
    """Attach the request to each sitemap, then delegate to Django's sitemap view."""
    for _sm in sitemaps.values():
        _sm.request = request
    return _sitemap_view(request, sitemaps)


class ApiEndpointSitemap(Sitemap):
    """The REST GET endpoints. Host comes from the request, not contrib.sites."""

    request = None
    changefreq = "weekly"
    priority = 0.5

    def get_domain(self, site=None):
        """Use the request host instead of the Sites framework."""
        if self.request is not None:
            return self.request.get_host()
        return super().get_domain(site)

    def items(self):
        """The GET endpoint paths."""
        return GET_ENDPOINTS

    def location(self, item):
        """The endpoint path, already absolute from the server root."""
        return item
'''
