"""Settings (vanilla shell, generated by racecar-start-django-project).

A single, generic, bootable Django settings module: `manage.py check` passes and
`manage.py runserver` serves an empty project. Database-light (sqlite default,
mysql via DB_TYPE=mysql, env-driven). It carries no surface, host-guard, or auth
configuration; racecar-create-server replaces this module with a project/settings/
package (shared base + per-surface api/mcp modules) when it composes the surfaces.

Install dev tools with `make install-dev`; `make install` installs the runtime."""
import os
from pathlib import Path

# settings.py -> project/ -> server root
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "dev-insecure-deploy-key")
DEBUG = os.environ.get("DJANGO_DEBUG", "1") == "1"
ALLOWED_HOSTS = os.environ.get(
    "DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1"
).split(",")
INTERNAL_IPS = ["127.0.0.1"]

# Dev tools, DEBUG-gated (the house DEBUG_APPS pattern). Single assignment (no
# augmented +=) so pylint keeps INSTALLED_APPS a module constant.
DEBUG_APPS = ["django_extensions"]
INSTALLED_APPS = [
    "django.contrib.staticfiles",
    *(DEBUG_APPS if DEBUG else []),
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
]

ROOT_URLCONF = "project.urls"
WSGI_APPLICATION = "project.wsgi.application"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {"context_processors": ["django.template.context_processors.request"]},
    }
]

# Database — the house pattern: sqlite (db.sqlite3) by default, mysql when
# DB_TYPE=mysql, env-driven. Database-light, but Django's machinery needs a real ENGINE.
MYSQL_SETTINGS = {
    "ENGINE": "django.db.backends.mysql",
    "NAME": os.getenv("DB_NAME", None),
    "USER": os.getenv("DB_USERNAME", None),
    "PASSWORD": os.getenv("DB_PASSWORD", None),
    "HOST": os.getenv("DB_HOST", "localhost"),
    "PORT": os.getenv("DB_PORT", ""),
    "OPTIONS": {"charset": "utf8mb4", "ssl": {"ca": os.getenv("DB_SSL_CERT", None)}},
}
SQLITE_SETTINGS = {
    "ENGINE": "django.db.backends.sqlite3",
    "NAME": BASE_DIR / "db.sqlite3",
}
if os.getenv("DB_TYPE", "sqlite").lower() == "mysql":
    DATABASES = {"default": MYSQL_SETTINGS}
else:
    DATABASES = {"default": SQLITE_SETTINGS}

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "static"
USE_TZ = True
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
