#!/usr/bin/env python3
"""Report how a project's .pre-commit-config.yaml drifts from base.

The mechanical floor for `/racecar-upgrade` (see upgrade/README.md, Procedure
step 1): it finds *where* a consuming project's config differs from the current
`templates/classic/` base, so the divergence can be classified Conform / Escalate.
It does not judge and it does not clobber; it only shows the differing lines. Run
from the racecar checkout against an adopter via --root; it is not synced to
adopters (it needs templates/classic/ to diff against).

Why only pre-commit, not the Makefile: under the Makefile fold (PACKAGING.md §7)
the build is split into the owned `Makefile` (thin, project-specific by design,
nothing to diff against a template) and the generated `racecar.mk` (regenerated by
`make sync`, never hand-edited, so it cannot drift). Makefile/shape consistency is
check_packaging.py's job (the `# racecar-shape:` stamp). What remains a hand-edited
single template is `.pre-commit-config.yaml`, so that is what this checks.

Why Python and not a shell drift check: a drift check is a file->base map, which in
bash means an associative array (`declare -A`), a bash 4 feature macOS bash 3.2 does
not support. In Python the map is a free, portable dict, matching racecar's "checks
are stdlib Python" doctrine. Pure stdlib (difflib + pathlib); runs anywhere python3
does.

Usage:
    python scripts/check_config_drift.py [--root <project>] [--strict]

--root defaults to CWD (the project to inspect). The base is this racecar
checkout's templates/classic/. Exit 0 always (advisory) unless --strict and drift
was found.
"""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

RACECAR_ROOT = Path(__file__).resolve().parent.parent
TEMPLATES = RACECAR_ROOT / "templates" / "classic"

# (project-relative path, template filename). A plain list of pairs, portable
# everywhere (the map racecar would have written with `declare -A` in bash).
PAIRS = ((".pre-commit-config.yaml", "pre-commit-config.yaml"),)


def unified_template_diff(project_file: Path, template_file: Path) -> list[str]:
    """Unified diff (base -> project), or [] if in sync.

    The one home for "how a vendored file differs from its racecar template". Reused by
    check_racecar_overrides.py for the racecar.mk byte-identity assertion so the two
    checks share a single diff mechanism.
    """
    base = template_file.read_text(encoding="utf-8").splitlines()
    proj = project_file.read_text(encoding="utf-8").splitlines()
    return list(
        difflib.unified_diff(base, proj, fromfile="base", tofile="project", lineterm="")
    )


def main(argv: list[str]) -> int:
    """Detect config drift against the canonical baseline; return an exit code."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--root", type=Path, default=Path.cwd())
    parser.add_argument("--strict", action="store_true", help="exit 1 if any drift")
    args = parser.parse_args(argv)
    root = args.root.expanduser().resolve()

    any_drift = False
    for rel, template_name in PAIRS:
        project_file = root / rel
        template_file = TEMPLATES / template_name
        if not template_file.is_file():
            print(f"check_config_drift: base missing: {template_file}", file=sys.stderr)
            continue
        if not project_file.is_file():
            print(f"  {rel}: absent in project (base ships one; add or declare why)")
            any_drift = True
            continue
        diff = unified_template_diff(project_file, template_file)
        if not diff:
            print(f"  {rel}: in sync with base")
            continue
        any_drift = True
        print(f"  {rel}: drifts from base (classify each: Conform / Escalate)")
        for line in diff:
            print(f"    {line}")

    if not any_drift:
        print("check_config_drift: OK (no pre-commit drift)")
        return 0
    print(
        "check_config_drift: drift found (advisory). Conform real drift to base, or "
        "Escalate a racecar defect. See upgrade/README.md."
    )
    return 1 if args.strict else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
